In [90]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6],[1,7], [3,400],[2,54],[12,23],[3,5], [3,400],[2,54],[12,23],[12,5]])

print a
np.array_split(a,5)

[[  1   2]
 [  3   4]
 [  5   6]
 [  1   7]
 [  3 400]
 [  2  54]
 [ 12  23]
 [  3   5]
 [  3 400]
 [  2  54]
 [ 12  23]
 [ 12   5]]


[array([[1, 2],
        [3, 4],
        [5, 6]]), array([[  1,   7],
        [  3, 400],
        [  2,  54]]), array([[12, 23],
        [ 3,  5]]), array([[  3, 400],
        [  2,  54]]), array([[12, 23],
        [12,  5]])]

In [40]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12], [3,9,7,10], [3,9,7,10]])
print a**2
print b**2

print np.dot(a,b.transpose())

print np.dot([1,2,3,4], [1,2,3,4])


print a**2 - b**2

[[ 1  4  9 16]
 [25 36 49 64]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [  9  81  49 100]
 [  9  81  49 100]]
[[ 30  70 110  82  82]
 [ 70 174 278 198 198]]
30


ValueError: operands could not be broadcast together with shapes (2,4) (5,4) 

In [82]:
a = np.array

b = np.array([[1,2,3,4], [1,2,3,4], [1,2,3,4]])




print np.sum(b**2, axis = 1) + np.sum(a**2, axis = 1)[:, np.newaxis]

np.dot(a, b.T)
#b.T.shape

[[0 0 0]
 [0 0 0]]
